# Generated by Django 3.2.5 on 2021-07-24 01:26
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAddrWithCoord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coord_lat', models.DecimalField(decimal_places=10, max_digits=16)),
                ('coord_lng', models.DecimalField(decimal_places=10, max_digits=16)),
                ('formatted_address', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_term', models.CharField(max_length=256)),
                ('coord_record',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_term',
                                   to='geo_calc.googleaddrwithcoord')),
            ],
        ),
    ]

